In [1]:
import csv

# copied from https://automatetheboringstuff.com/chapter14/
def process_csv(filename):
    exampleFile = open(filename)
    exampleReader = csv.reader(exampleFile)
    exampleData = list(exampleReader)
    return exampleData

In [2]:
rows = process_csv('tornados.csv')

header = rows[0]
rows = rows[1:]
year_idx = header.index("year")

In [9]:
header

['year', 'id', 'location', 'speed']

In [31]:
# goal: key will be the year, the value will be how many
counts = {}

for row in rows:
    year = int(row[year_idx])
    if not year in counts:
        counts[year] = 0

    counts[year] += 1
    year_2000 += 1
    print("ROW", row)
    print("COUNTS", counts)
print(counts)

ROW ['2006', 'QPIQPWDP', 'site B', '175']
COUNTS {2006: 1}
ROW ['1996', 'MMMHKDDK', 'site B', '290']
COUNTS {2006: 1, 1996: 1}
ROW ['2016', 'QSCAPJBU', 'site B', '290']
COUNTS {2006: 1, 1996: 1, 2016: 1}
ROW ['2014', 'KKGOICYZ', 'site C', '122']
COUNTS {2006: 1, 1996: 1, 2016: 1, 2014: 1}
ROW ['2015', 'ZDMHZTXL', 'site A', '147']
COUNTS {2006: 1, 1996: 1, 2016: 1, 2014: 1, 2015: 1}
ROW ['2005', 'FEBIJZIF', 'site A', '198']
COUNTS {2006: 1, 1996: 1, 2016: 1, 2014: 1, 2015: 1, 2005: 1}
ROW ['2002', 'EYIVKEWL', 'site B', '199']
COUNTS {2006: 1, 1996: 1, 2016: 1, 2014: 1, 2015: 1, 2005: 1, 2002: 1}
ROW ['1995', 'JDUTRHFQ', 'site A', '281']
COUNTS {2006: 1, 1996: 1, 2016: 1, 2014: 1, 2015: 1, 2005: 1, 2002: 1, 1995: 1}
ROW ['1997', 'NSCJTEAU', 'site B', '222']
COUNTS {2006: 1, 1996: 1, 2016: 1, 2014: 1, 2015: 1, 2005: 1, 2002: 1, 1995: 1, 1997: 1}
ROW ['2005', 'AWLDIUCW', 'site A', '173']
COUNTS {2006: 1, 1996: 1, 2016: 1, 2014: 1, 2015: 1, 2005: 2, 2002: 1, 1995: 1, 1997: 1}
ROW ['1996', 'JRHLYGLS', 'site C', '238']
COUNTS {2006: 1, 1996: 2, 2016: 1, 2014: 1, 2015: 1, 2005: 2, 2002: 1, 1995: 1, 1997: 1}
ROW ['2001', 'QRYMLENE', 'site C', '174']
COUNTS {2006: 1, 1996: 2, 2016: 1, 2014: 1, 2015: 1, 2005: 2, 2002: 1, 1995: 1, 1997: 1, 2001: 1}
ROW ['1995', 'RCAOONFD', 'site A', '198']
COUNTS {2006: 1, 1996: 2, 2016: 1, 2014: 1, 2015: 1, 2005: 2, 2002: 1, 1995: 2, 1997: 1, 2001: 1}
ROW ['2002', 'IZXLGNRJ', 'site C', '269']
COUNTS {2006: 1, 1996: 2, 2016: 1, 2014: 1, 2015: 1, 2005: 2, 2002: 2, 1995: 2, 1997: 1, 2001: 1}
ROW ['2011', 'AUJLPQWN', 'site B', '243']
COUNTS {2006: 1, 1996: 2, 2016: 1, 2014: 1, 2015: 1, 2005: 2, 2002: 2, 1995: 2, 1997: 1, 2001: 1, 2011: 1}
ROW ['1995', 'XCBWVUIF', 'site A', '234']
COUNTS {2006: 1, 1996: 2, 2016: 1, 2014: 1, 2015: 1, 2005: 2, 2002: 2, 1995: 3, 1997: 1, 2001: 1, 2011: 1}
ROW ['2010', 'SZRUOPIH', 'site B', '201']
COUNTS {2006: 1, 1996: 2, 2016: 1, 2014: 1, 2015: 1, 2005: 2, 2002: 2, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1}
ROW ['2016', 'JQPYBXEI', 'site A', '139']
COUNTS {2006: 1, 1996: 2, 2016: 2, 2014: 1, 2015: 1, 2005: 2, 2002: 2, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1}
ROW ['2016', 'BJDRTWIW', 'site A', '286']
COUNTS {2006: 1, 1996: 2, 2016: 3, 2014: 1, 2015: 1, 2005: 2, 2002: 2, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1}
ROW ['2005', 'CWGFYTZZ', 'site C', '109']
COUNTS {2006: 1, 1996: 2, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 2, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1}
ROW ['2017', 'LIBFCJBB', 'site C', '181']
COUNTS {2006: 1, 1996: 2, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 2, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1, 2017: 1}
ROW ['1996', 'WIMYUNGE', 'site A', '187']
COUNTS {2006: 1, 1996: 3, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 2, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1, 2017: 1}
ROW ['2017', 'CNMZERWF', 'site C', '218']
COUNTS {2006: 1, 1996: 3, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 2, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1, 2017: 2}
ROW ['2008', 'FUBXASWR', 'site B', '255']
COUNTS {2006: 1, 1996: 3, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 2, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1, 2017: 2, 2008: 1}
ROW ['1996', 'LJJJYSDQ', 'site A', '209']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 2, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1, 2017: 2, 2008: 1}
ROW ['2002', 'EONEPHOZ', 'site A', '213']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 3, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1, 2017: 2, 2008: 1}
ROW ['2003', 'NQSHEURP', 'site C', '155']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 3, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1, 2017: 2, 2008: 1, 2003: 1}
ROW ['2003', 'VFIBJORY', 'site B', '240']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 3, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1, 2017: 2, 2008: 1, 2003: 2}
ROW ['2004', 'KRMJSZGY', 'site C', '137']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 3, 1995: 3, 1997: 1, 2001: 1, 2011: 1, 2010: 1, 2017: 2, 2008: 1, 2003: 2, 2004: 1}
ROW ['2001', 'VTBWHKRH', 'site B', '271']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 3, 1995: 3, 1997: 1, 2001: 2, 2011: 1, 2010: 1, 2017: 2, 2008: 1, 2003: 2, 2004: 1}
ROW ['2008', 'TVEGOJAM', 'site C', '272']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 3, 2002: 3, 1995: 3, 1997: 1, 2001: 2, 2011: 1, 2010: 1, 2017: 2, 2008: 2, 2003: 2, 2004: 1}
ROW ['2005', 'EXXPOMSB', 'site C', '236']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 4, 2002: 3, 1995: 3, 1997: 1, 2001: 2, 2011: 1, 2010: 1, 2017: 2, 2008: 2, 2003: 2, 2004: 1}
ROW ['2013', 'GTKGJLKN', 'site A', '220']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 4, 2002: 3, 1995: 3, 1997: 1, 2001: 2, 2011: 1, 2010: 1, 2017: 2, 2008: 2, 2003: 2, 2004: 1, 2013: 1}
ROW ['2009', 'VLEHBLKH', 'site B', '141']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 4, 2002: 3, 1995: 3, 1997: 1, 2001: 2, 2011: 1, 2010: 1, 2017: 2, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1}
ROW ['2017', 'YNBKDYTA', 'site A', '179']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 4, 2002: 3, 1995: 3, 1997: 1, 2001: 2, 2011: 1, 2010: 1, 2017: 3, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1}
ROW ['1998', 'DIBERSNP', 'site A', '240']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 4, 2002: 3, 1995: 3, 1997: 1, 2001: 2, 2011: 1, 2010: 1, 2017: 3, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1}
ROW ['2001', 'ZSPSCPBT', 'site C', '259']
COUNTS {2006: 1, 1996: 4, 2016: 3, 2014: 1, 2015: 1, 2005: 4, 2002: 3, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 1, 2017: 3, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1}
ROW ['2016', 'KOBWSFXW', 'site A', '186']
COUNTS {2006: 1, 1996: 4, 2016: 4, 2014: 1, 2015: 1, 2005: 4, 2002: 3, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 1, 2017: 3, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1}
ROW ['2010', 'CETAQQXF', 'site B', '202']
COUNTS {2006: 1, 1996: 4, 2016: 4, 2014: 1, 2015: 1, 2005: 4, 2002: 3, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 3, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1}
ROW ['2007', 'DBEESDMM', 'site A', '159']
COUNTS {2006: 1, 1996: 4, 2016: 4, 2014: 1, 2015: 1, 2005: 4, 2002: 3, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 3, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1, 2007: 1}
ROW ['2017', 'YWHUCOUS', 'site B', '194']
COUNTS {2006: 1, 1996: 4, 2016: 4, 2014: 1, 2015: 1, 2005: 4, 2002: 3, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1, 2007: 1}
ROW ['2014', 'CCCCYZBY', 'site C', '264']
COUNTS {2006: 1, 1996: 4, 2016: 4, 2014: 2, 2015: 1, 2005: 4, 2002: 3, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1, 2007: 1}
ROW ['2002', 'VKANHNPC', 'site A', '175']
COUNTS {2006: 1, 1996: 4, 2016: 4, 2014: 2, 2015: 1, 2005: 4, 2002: 4, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1, 2007: 1}
ROW ['2007', 'DSSUCXOI', 'site A', '265']
COUNTS {2006: 1, 1996: 4, 2016: 4, 2014: 2, 2015: 1, 2005: 4, 2002: 4, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1, 2007: 2}
ROW ['2014', 'EWLAXYVH', 'site C', '153']
COUNTS {2006: 1, 1996: 4, 2016: 4, 2014: 3, 2015: 1, 2005: 4, 2002: 4, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1, 2007: 2}
ROW ['2014', 'BPNKITVS', 'site A', '296']
COUNTS {2006: 1, 1996: 4, 2016: 4, 2014: 4, 2015: 1, 2005: 4, 2002: 4, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1, 2007: 2}
ROW ['2015', 'YDPQWWGV', 'site B', '130']
COUNTS {2006: 1, 1996: 4, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 4, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 1, 1998: 1, 2007: 2}
ROW ['2009', 'JRKTSFOU', 'site A', '112']
COUNTS {2006: 1, 1996: 4, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 4, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 2, 1998: 1, 2007: 2}
ROW ['1996', 'TOXIMTKE', 'site C', '290']
COUNTS {2006: 1, 1996: 5, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 4, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 2, 1998: 1, 2007: 2}
ROW ['2002', 'QZKYNJFZ', 'site C', '250']
COUNTS {2006: 1, 1996: 5, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 5, 1995: 3, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 2, 1998: 1, 2007: 2}
ROW ['1995', 'KYUONPMV', 'site C', '187']
COUNTS {2006: 1, 1996: 5, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 5, 1995: 4, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 1, 2009: 2, 1998: 1, 2007: 2}
ROW ['2013', 'RQYVUUGR', 'site A', '259']
COUNTS {2006: 1, 1996: 5, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 5, 1995: 4, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 2, 2003: 2, 2004: 1, 2013: 2, 2009: 2, 1998: 1, 2007: 2}
ROW ['2008', 'PHSPFJVR', 'site A', '257']
COUNTS {2006: 1, 1996: 5, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 5, 1995: 4, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 3, 2003: 2, 2004: 1, 2013: 2, 2009: 2, 1998: 1, 2007: 2}
ROW ['2009', 'ZUCZYBOC', 'site A', '258']
COUNTS {2006: 1, 1996: 5, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 5, 1995: 4, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 3, 2003: 2, 2004: 1, 2013: 2, 2009: 3, 1998: 1, 2007: 2}
ROW ['2004', 'DWIDLQEZ', 'site A', '287']
COUNTS {2006: 1, 1996: 5, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 5, 1995: 4, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 3, 2003: 2, 2004: 2, 2013: 2, 2009: 3, 1998: 1, 2007: 2}
ROW ['1995', 'EMCQGXEG', 'site B', '155']
COUNTS {2006: 1, 1996: 5, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 5, 1995: 5, 1997: 1, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 3, 2003: 2, 2004: 2, 2013: 2, 2009: 3, 1998: 1, 2007: 2}
ROW ['1997', 'MEYDGPRX', 'site A', '272']
COUNTS {2006: 1, 1996: 5, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 5, 1995: 5, 1997: 2, 2001: 3, 2011: 1, 2010: 2, 2017: 4, 2008: 3, 2003: 2, 2004: 2, 2013: 2, 2009: 3, 1998: 1, 2007: 2}
ROW ['2011', 'TLSAVUXI', 'site A', '230']
COUNTS {2006: 1, 1996: 5, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 5, 1995: 5, 1997: 2, 2001: 3, 2011: 2, 2010: 2, 2017: 4, 2008: 3, 2003: 2, 2004: 2, 2013: 2, 2009: 3, 1998: 1, 2007: 2}
{2006: 1, 1996: 5, 2016: 4, 2014: 4, 2015: 2, 2005: 4, 2002: 5, 1995: 5, 1997: 2, 2001: 3, 2011: 2, 2010: 2, 2017: 4, 2008: 3, 2003: 2, 2004: 2, 2013: 2, 2009: 3, 1998: 1, 2007: 2}

In [27]:
years_list = list(counts.keys())
years_list.sort()
years_list[:5]

[1995, 1996, 1997, 1998, 2001]

In [30]:
for year in years_list:
    print(year, "*" * counts[year])

1995 *****
1996 *****
1997 **
1998 *
2001 ***
2002 *****
2003 **
2004 **
2005 ****
2006 *
2007 **
2008 ***
2009 ***
2010 **
2011 **
2013 **
2014 ****
2015 **
2016 ****
2017 ****