In [1]:
import sqlite3

In [2]:
conn = sqlite3.connect("bus.db")
conn

In [11]:
# EXAMPLE 1: total ridership with tuples
tuple_iterator = conn.execute("select * from sqlite_master")
tuple_iterator

In [4]:
for row in tuple_iterator:
    print(row)

('table', 'boarding', 'boarding', 2, 'CREATE TABLE "boarding" (\n"index" INTEGER,\n  "StopID" INTEGER,\n  "Route" INTEGER,\n  "Lat" REAL,\n  "Lon" REAL,\n  "DailyBoardings" REAL\n)')
('index', 'ix_boarding_index', 'boarding', 3, 'CREATE INDEX "ix_boarding_index"ON "boarding" ("index")')
('table', 'routes', 'routes', 55, 'CREATE TABLE "routes" (\n"index" INTEGER,\n  "OBJECTID" INTEGER,\n  "trips_routes_route_id" INTEGER,\n  "route_short_name" INTEGER,\n  "route_url" TEXT,\n  "ShapeSTLength" REAL\n)')
('index', 'ix_routes_index', 'routes', 57, 'CREATE INDEX "ix_routes_index"ON "routes" ("index")')

In [5]:
tuple_iterator = conn.execute("select * from sqlite_master")
list(tuple_iterator)

[('table',
  'boarding',
  'boarding',
  2,
  'CREATE TABLE "boarding" (\n"index" INTEGER,\n  "StopID" INTEGER,\n  "Route" INTEGER,\n  "Lat" REAL,\n  "Lon" REAL,\n  "DailyBoardings" REAL\n)'),
 ('index',
  'ix_boarding_index',
  'boarding',
  3,
  'CREATE INDEX "ix_boarding_index"ON "boarding" ("index")'),
 ('table',
  'routes',
  'routes',
  55,
  'CREATE TABLE "routes" (\n"index" INTEGER,\n  "OBJECTID" INTEGER,\n  "trips_routes_route_id" INTEGER,\n  "route_short_name" INTEGER,\n  "route_url" TEXT,\n  "ShapeSTLength" REAL\n)'),
 ('index',
  'ix_routes_index',
  'routes',
  57,
  'CREATE INDEX "ix_routes_index"ON "routes" ("index")')]

In [6]:
results = conn.execute("SELECT DailyBoardings FROM boarding")
results

In [7]:
results = list(results)
results

[(1.03,),
 (0.11,),
 (0.34,),
 (10.59,),
 (3.11,),
 (2.23,),
 (0.11,),
 (1.36,),
 (18.9,),
 (1.35,),
 (31.15,),
 (6.69,),
 (1.46,),
 (13.45,),
 (37.75,),
 (16.03,),
 (5.74,),
 (16.34,),
 (16.7,),
 (10.57,),
 (32.96,),
 (0.57,),
 (7.56,),
 (5.12,),
 (5.34,),
 (10.87,),
 (31.11,),
 (3.24,),
 (4.95,),
 (0.89,),
 (0.57,),
 (0.34,),
 (1.24,),
 (0.45,),
 (2.46,),
 (10.13,),
 (2.45,),
 (2.78,),
 (4.02,),
 (7.09,),
 (0.56,),
 (0.22,),
 (10.01,),
 (15.15,),
 (5.23,),
 (8.58,),
 (16.37,),
 (2.56,),
 (0.9,),
 (4.11,),
 (0.11,),
 (3.89,),
 (6.79,),
 (1.0,),
 (33.78,),
 (14.63,),
 (16.09,),
 (0.33,),
 (1.26,),
 (1.12,),
 (1.24,),
 (0.78,),
 (5.57,),
 (3.69,),
 (5.4,),
 (1.67,),
 (0.57,),
 (3.6,),
 (0.89,),
 (1.11,),
 (0.34,),
 (0.79,),
 (0.11,),
 (11.34,),
 (4.79,),
 (9.51,),
 (1.92,),
 (2.23,),
 (6.01,),
 (11.48,),
 (0.67,),
 (0.34,),
 (0.11,),
 (0.22,),
 (2.0,),
 (11.55,),
 (16.72,),
 (0.22,),
 (0.79,),
 (1.23,),
 (0.56,),
 (25.3,),
 (12.25,),
 (21.03,),
 (0.11,),
 (38.97,),
 (33.89,),
 (8.56,),
 (4.11,),
 (19.71,),
 (1.33,),
 (0.68,),
 (14.38,),
 (11.47,),
 (7.57,),
 (4.45,),
 (37.02,),
 (2.23,),
 (5.11,),
 (3.94,),
 (1.81,),
 (0.34,),
 (2.57,),
 (31.18,),
 (57.2,),
 (1.67,),
 (0.34,),
 (10.02,),
 (0.89,),
 (4.05,),
 (9.7,),
 (9.47,),
 (12.69,),
 (0.22,),
 (4.78,),
 (20.5,),
 (0.11,),
 (0.91,),
 (0.22,),
 (0.22,),
 (1.57,),
 (0.11,),
 (46.15,),
 (31.57,),
 (37.64,),
 (56.86,),
 (2.79,),
 (0.56,),
 (18.21,),
 (29.82,),
 (3.15,),
 (7.37,),
 (8.79,),
 (5.25,),
 (5.25,),
 (8.73,),
 (5.72,),
 (4.59,),
 (7.02,),
 (18.95,),
 (1.12,),
 (1.45,),
 (1.38,),
 (37.35,),
 (8.83,),
 (10.01,),
 (0.56,),
 (7.46,),
 (4.69,),
 (1.8,),
 (0.23,),
 (0.11,),
 (0.35,),
 (24.63,),
 (38.24,),
 (29.96,),
 (89.1,),
 (64.0,),
 (1.79,),
 (6.17,),
 (8.83,),
 (10.8,),
 (8.12,),
 (1.26,),
 (1.9,),
 (0.22,),
 (0.67,),
 (0.9,),
 (0.45,),
 (0.67,),
 (0.22,),
 (0.11,),
 (0.45,),
 (13.4,),
 (2.45,),
 (6.91,),
 (0.33,),
 (0.11,),
 (0.45,),
 (3.23,),
 (10.03,),
 (10.47,),
 (0.45,),
 (6.47,),
 (26.06,),
 (22.86,),
 (5.03,),
 (10.8,),
 (0.11,),
 (5.39,),
 (3.24,),
 (0.79,),
 (1.46,),
 (0.78,),
 (1.45,),
 (41.62,),
 (0.57,),
 (54.96,),
 (3.89,),
 (0.34,),
 (0.23,),
 (0.22,),
 (7.69,),
 (1.01,),
 (0.11,),
 (0.34,),
 (2.47,),
 (0.11,),
 (36.24,),
 (12.18,),
 (14.29,),
 (1.8,),
 (1.34,),
 (12.57,),
 (15.01,),
 (2.47,),
 (5.44,),
 (14.37,),
 (4.22,),
 (0.57,),
 (34.45,),
 (7.82,),
 (8.44,),
 (1.38,),
 (1.57,),
 (1.58,),
 (1.34,),
 (6.46,),
 (0.23,),
 (0.33,),
 (11.59,),
 (7.35,),
 (0.89,),
 (1.01,),
 (1.22,),
 (15.34,),
 (0.45,),
 (9.06,),
 (16.72,),
 (3.9,),
 (7.14,),
 (7.58,),
 (1.23,),
 (4.39,),
 (2.18,),
 (0.34,),
 (0.11,),
 (1.13,),
 (0.22,),
 (2.13,),
 (0.78,),
 (2.34,),
 (0.46,),
 (0.22,),
 (6.12,),
 (8.6,),
 (0.45,),
 (0.22,),
 (1.67,),
 (0.34,),
 (0.23,),
 (0.23,),
 (4.0,),
 (11.67,),
 (0.11,),
 (9.24,),
 (8.38,),
 (15.08,),
 (5.34,),
 (8.69,),
 (5.01,),
 (7.91,),
 (6.93,),
 (6.86,),
 (21.79,),
 (4.84,),
 (0.34,),
 (8.56,),
 (7.24,),
 (2.67,),
 (7.59,),
 (36.79,),
 (10.25,),
 (8.83,),
 (11.37,),
 (6.34,),
 (23.12,),
 (12.03,),
 (2.15,),
 (24.0,),
 (14.06,),
 (25.42,),
 (10.84,),
 (16.99,),
 (0.11,),
 (3.38,),
 (5.13,),
 (8.81,),
 (1.45,),
 (5.63,),
 (1.49,),
 (0.78,),
 (0.22,),
 (0.56,),
 (1.0,),
 (41.8,),
 (25.17,),
 (13.59,),
 (0.11,),
 (14.04,),
 (7.77,),
 (12.12,),
 (10.36,),
 (0.45,),
 (1.93,),
 (11.23,),
 (3.67,),
 (0.45,),
 (2.38,),
 (9.03,),
 (0.89,),
 (0.79,),
 (0.11,),
 (5.57,),
 (0.23,),
 (0.45,),
 (4.34,),
 (7.45,),
 (15.59,),
 (6.23,),
 (33.57,),
 (34.41,),
 (14.58,),
 (31.49,),
 (5.24,),
 (15.12,),
 (12.58,),
 (6.23,),
 (26.28,),
 (13.03,),
 (3.78,),
 (2.22,),
 (6.68,),
 (0.67,),
 (2.24,),
 (22.96,),
 (20.46,),
 (14.92,),
 (22.63,),
 (1.23,),
 (0.34,),
 (11.51,),
 (13.84,),
 (1.35,),
 (2.9,),
 (2.82,),
 (4.02,),
 (3.57,),
 (6.27,),
 (2.81,),
 (4.36,),
 (6.23,),
 (6.46,),
 (0.78,),
 (1.47,),
 (20.96,),
 (0.78,),
 (1.8,),
 (1.15,),
 (0.67,),
 (0.67,),
 (2.72,),
 (13.84,),
 (17.48,),
 (0.11,),
 (0.11,),
 (23.75,),
 (3.24,),
 (2.03,),
 (1.0,),
 (1.8,),
 (1.13,),
 (1.0,),
 (6.12,),
 (1.84,),
 (0.9,),
 (0.11,),
 (0.33,),
 (2.67,),
 (0.33,),
 (0.45,),
 (3.12,),
 (7.12,),
 (0.11,),
 (8.46,),
 (4.45,),
 (3.12,),
 (0.33,),
 (1.02,),
 (25.31,),
 (14.19,),
 (33.76,),
 (0.22,),
 (1.84,),
 (0.22,),
 (2.25,),
 (2.18,),
 (4.69,),
 (1.56,),
 (0.11,),
 (4.98,),
 (0.23,),
 (0.45,),
 (0.22,),
 (36.34,),
 (16.82,),
 (43.74,),
 (0.57,),
 (59.13,),
 (4.78,),
 (0.11,),
 (1.7,),
 (5.78,),
 (10.25,),
 (1.67,),
 (41.92,),
 (8.6,),
 (12.38,),
 (3.79,),
 (0.78,),
 (3.15,),
 (0.9,),
 (1.23,),
 (1.0,),
 (0.67,),
 (24.98,),
 (6.59,),
 (11.03,),
 (3.33,),
 (0.79,),
 (0.23,),
 (0.67,),
 (14.16,),
 (5.57,),
 (14.69,),
 (0.57,),
 (22.75,),
 (1.89,),
 (23.61,),
 (26.15,),
 (19.23,),
 (1.46,),
 (4.98,),
 (14.45,),
 (10.13,),
 (3.34,),
 (3.28,),
 (3.74,),
 (4.68,),
 (8.9,),
 (0.78,),
 (0.11,),
 (2.79,),
 (0.78,),
 (1.24,),
 (0.22,),
 (0.22,),
 (8.91,),
 (14.36,),
 (7.46,),
 (7.91,),
 (2.03,),
 (34.35,),
 (2.81,),
 (12.01,),
 (7.12,),
 (1.24,),
 (1.56,),
 (0.45,),
 (1.78,),
 (0.23,),
 (3.22,),
 (2.34,),
 (2.11,),
 (4.98,),
 (0.11,),
 (44.82,),
 (7.93,),
 (14.07,),
 (5.39,),
 (2.92,),
 (2.03,),
 (1.79,),
 (26.13,),
 (21.27,),
 (22.88,),
 (5.35,),
 (4.02,),
 (2.59,),
 (22.9,),
 (22.61,),
 (8.9,),
 (25.71,),
 (1.23,),
 (0.45,),
 (0.23,),
 (0.9,),
 (0.11,),
 (2.78,),
 (0.22,),
 (2.12,),
 (3.35,),
 (8.35,),
 (2.34,),
 (3.1,),
 (0.11,),
 (10.81,),
 (19.27,),
 (40.65,),
 (2.12,),
 (2.89,),
 (9.01,),
 (36.81,),
 (0.89,),
 (0.67,),
 (0.34,),
 (0.11,),
 (11.78,),
 (3.49,),
 (1.02,),
 (1.51,),
 (41.8,),
 (36.58,),
 (21.27,),
 (30.41,),
 (88.64,),
 (3.13,),
 (1.57,),
 (13.18,),
 (18.23,),
 (13.13,),
 (0.67,),
 (7.23,),
 (3.91,),
 (0.34,),
 (12.84,),
 (16.45,),
 (11.94,),
 (16.31,),
 (8.4,),
 (19.19,),
 (23.05,),
 (71.31,),
 (32.08,),
 (0.92,),
 (0.56,),
 (0.91,),
 (1.56,),
 (3.56,),
 (2.0,),
 (0.23,),
 (3.83,),
 (3.34,),
 (0.34,),
 (1.01,),
 (0.89,),
 (0.11,),
 (0.11,),
 (0.11,),
 (2.0,),
 (0.67,),
 (0.11,),
 (7.8,),
 (6.9,),
 (3.21,),
 (1.67,),
 (1.13,),
 (50.14,),
 (32.18,),
 (19.82,),
 (5.56,),
 (10.47,),
 (5.56,),
 (1.46,),
 (5.13,),
 (7.13,),
 (1.56,),
 (0.11,),
 (3.38,),
 (0.67,),
 (32.33,),
 (21.16,),
 (59.43,),
 (0.34,),
 (64.76,),
 (3.22,),
 (61.64,),
 (9.56,),
 (9.35,),
 (2.94,),
 (7.24,),
 (4.58,),
 (4.84,),
 (1.56,),
 (18.95,),
 (5.59,),
 (7.65,),
 (1.46,),
 (0.78,),
 (0.11,),
 (0.22,),
 (3.23,),
 (1.0,),
 (0.22,),
 (0.9,),
 (0.33,),
 (1.74,),
 (0.78,),
 (20.32,),
 (12.13,),
 (1.68,),
 (2.24,),
 (1.56,),
 (29.91,),
 (31.74,),
 (9.46,),
 (35.91,),
 (25.87,),
 (4.25,),
 (1.91,),
 (1.15,),
 (1.24,),
 (1.12,),
 (1.89,),
 (3.24,),
 (5.74,),
 (0.56,),
 (1.01,),
 (2.0,),
 (0.45,),
 (0.11,),
 (10.45,),
 (4.16,),
 (0.45,),
 (3.51,),
 (15.16,),
 (31.41,),
 (34.83,),
 (1.61,),
 (46.4,),
 (8.24,),
 (5.71,),
 (6.59,),
 (2.13,),
 (1.15,),
 (0.56,),
 (23.46,),
 (1.12,),
 (7.7,),
 (1.67,),
 (2.9,),
 (0.11,),
 (1.35,),
 (0.22,),
 (0.23,),
 (1.45,),
 (20.61,),
 (7.68,),
 (2.01,),
 (2.03,),
 (22.29,),
 (18.36,),
 (4.79,),
 (0.56,),
 (21.74,),
 (1.34,),
 (2.03,),
 (0.69,),
 (0.9,),
 (0.89,),
 (5.67,),
 (1.7,),
 (1.11,),
 (2.78,),
 (1.22,),
 (4.24,),
 (46.05,),
 (5.35,),
 (16.36,),
 (6.08,),
 (2.67,),
 (4.11,),
 (5.35,),
 (0.22,),
 (1.93,),
 (1.22,),
 (0.11,),
 (46.48,),
 (10.36,),
 (6.47,),
 (8.22,),
 (1.78,),
 (3.12,),
 (0.67,),
 (0.45,),
 (9.24,),
 (10.46,),
 (3.44,),
 (0.78,),
 (1.47,),
 (21.74,),
 (15.7,),
 (19.48,),
 (0.34,),
 (26.92,),
 (1.67,),
 (9.74,),
 (8.78,),
 (0.89,),
 (11.6,),
 (14.72,),
 (3.13,),
 (72.82,),
 (99.5,),
 (5.79,),
 (6.23,),
 (0.11,),
 (100.05,),
 (18.45,),
 (4.34,),
 (120.73,),
 (86.27,),
 (1.56,),
 (83.38,),
 (5.0,),
 (3.78,),
 (177.54,),
 (57.81,),
 (37.24,),
 (32.02,),
 (41.69,),
 (270.14,),
 (7.15,),
 (0.23,),
 (0.23,),
 (4.56,),
 (0.56,),
 (44.15,),
 (53.46,),
 (41.8,),
 (248.24,),
 (28.54,),
 (0.45,),
 (5.4,),
 (2.93,),
 (3.8,),
 (74.24,),
 (167.49,),
 (46.7,),
 (7.87,),
 (33.13,),
 (32.15,),
 (2.89,),
 (2.79,),
 (9.16,),
 (38.91,),
 (0.56,),
 (0.56,),
 (1.0,),
 (2.9,),
 (0.22,),
 (5.11,),
 (3.35,),
 (27.2,),
 (14.76,),
 (9.93,),
 (137.44,),
 (78.57,),
 (0.9,),
 (0.11,),
 (61.81,),
 (22.4,),
 (15.02,),
 (12.73,),
 (12.57,),
 (1.67,),
 (0.67,),
 (16.39,),
 (1.0,),
 (4.12,),
 (6.13,),
 (2.23,),
 (3.69,),
 (0.68,),
 (0.33,),
 (8.34,),
 (2.12,),
 (11.07,),
 (36.6,),
 (38.28,),
 (12.96,),
 (321.06,),
 (33.22,),
 (45.52,),
 (1.11,),
 (0.11,),
 (0.22,),
 (0.11,),
 (6.03,),
 (2.57,),
 (10.15,),
 (0.11,),
 (2.57,),
 (9.81,),
 (6.91,),
 (2.68,),
 (8.16,),
 (3.23,),
 (0.45,),
 (88.39,),
 (233.26,),
 (41.19,),
 (2.81,),
 (35.83,),
 (40.18,),
 (7.26,),
 (0.45,),
 (0.22,),
 (3.35,),
 (8.47,),
 (0.22,),
 (2.36,),
 (0.56,),
 (95.42,),
 (92.26,),
 (10.28,),
 (2.81,),
 (39.95,),
 (5.97,),
 (0.79,),
 (6.76,),
 (6.92,),
 (21.83,),
 (12.23,),
 (12.87,),
 (35.78,),
 (45.63,),
 (0.22,),
 (0.45,),
 (0.22,),
 (1.01,),
 (34.99,),
 (39.31,),
 (35.34,),
 (8.16,),
 (984.51,),
 (1.01,),
 (0.45,),
 (1.12,),
 (10.25,),
 (9.68,),
 (0.11,),
 (7.88,),
 (0.23,),
 (0.11,),
 (1.24,),
 (1.34,),
 (7.72,),
 (6.73,),
 (6.04,),
 (14.27,),
 (10.61,),
 (6.65,),
 (4.02,),
 (0.89,),
 (1.0,),
 (0.11,),
 (28.24,),
 (0.78,),
 (0.11,),
 (0.11,),
 (2.03,),
 (1.0,),
 (1.79,),
 (0.79,),
 (0.11,),
 (0.22,),
 (0.11,),
 (1.56,),
 (4.7,),
 (7.52,),
 (12.53,),
 (5.24,),
 (5.8,),
 (1.8,),
 (5.01,),
 (0.67,),
 (1.0,),
 (0.33,),
 (8.14,),
 (1.11,),
 (6.67,),
 (3.8,),
 (45.03,),
 (3.8,),
 (13.27,),
 (1.56,),
 (4.45,),
 (2.9,),
 (7.6,),
 (52.15,),
 (44.97,),
 (9.5,),
 (455.02,),
 (3.57,),
 (0.33,),
 (0.22,),
 (0.11,),
 (2.36,),
 (0.11,),
 (1.01,),
 (8.25,),
 (5.79,),
 (0.67,),
 (1.23,),
 (4.61,),
 (0.56,),
 (1.92,),
 (1.34,),
 (1.46,),
 (2.47,),
 (3.13,),
 (0.22,),
 (0.11,),
 (0.11,),
 (5.01,),
 (0.45,),
 (0.23,),
 (1.22,),
 (1.01,),
 (0.11,),
 (10.24,),
 (0.56,),
 (2.01,),
 (1.67,),
 (1.23,),
 (5.02,),
 (0.89,),
 (0.23,),
 (0.56,),
 (8.03,),
 (0.33,),
 (6.37,),
 (0.33,),
 (231.85,),
 (129.98,),
 (111.16,),
 (83.36,),
 (561.96,),
 (4.89,),
 (1.79,),
 (4.37,),
 (3.14,),
 (4.47,),
 (2.68,),
 (0.34,),
 (0.56,),
 (1.46,),
 (0.34,),
 (2.02,),
 (3.14,),
 (3.02,),
 (0.67,),
 (20.29,),
 (17.14,),
 (4.16,),
 (1.24,),
 (1.23,),
 (25.76,),
 (5.89,),
 (2.33,),
 (1.78,),
 (0.22,),
 (0.22,),
 (5.46,),
 (1.56,),
 (0.23,),
 (0.45,),
 (11.26,),
 (55.37,),
 ...]

In [10]:
total = 0
for row in results:
    total += row[0]
total

55987.17999999951

In [12]:
# EXAMPLE 2: farthest west, using Pandas

In [13]:
import pandas as pd

In [14]:
# pd.read_sql(QUERY, CONNECTION)

In [24]:
# use triple quotes to split across lines
query = """
SELECT *
FROM boarding
ORDER BY Lon ASC, Lat DESC
LIMIT 1
"""
df = pd.read_sql(query, conn)
df

   index  StopID  Route        Lat        Lon  DailyBoardings
0   3489    4400     55  42.995476 -89.564243           59.31

In [25]:
# EXAMPLE 3: center of mass of bus system

In [27]:
# use triple quotes to split across lines
query = """
SELECT Lon, Lat
FROM boarding
"""
df = pd.read_sql(query, conn)
df.head()

         Lon        Lat
0 -89.385427  43.073655
1 -89.385427  43.073655
2 -89.385427  43.073655
3 -89.340021  43.106465
4 -89.369993  43.077867

In [28]:
df.mean()

Lon   -89.402466
Lat    43.075374
dtype: float64

In [29]:
list(df.mean())

[-89.4024664433534, 43.075374427492534]